// Syncs everything this game takes from the Sand to GPU course repository:
//   generated/quiz-data.js  <- course/quizzes/*.json
//   generated/figures.js    <- course/visuals (rendered with the course's own renderer)
//   course/widgets/*.js, course/styles.css, course/widget-layout.js, course/section-figures.css
// Usage: node tools/sync-course.js            (expects ../sand-to-gpu next to this repo)
//        COURSE_DIR=/path/to/sand-to-gpu node tools/sync-course.js
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const COURSE = path.resolve(process.env.COURSE_DIR || path.join(ROOT, '..', 'sand-to-gpu'));
if (!fs.existsSync(path.join(COURSE, 'course', 'quizzes'))) { console.error('Course repo not found at ' + COURSE + '. Clone https://github.com/DicksonWu654/sand-to-gpu next to this repo or set COURSE_DIR.'); process.exit(1); }
fs.mkdirSync(path.join(ROOT, 'generated'), { recursive: true });
fs.mkdirSync(path.join(ROOT, 'course', 'widgets'), { recursive: true });

// 1. quizzes
const QUIZ_DIR = path.join(COURSE, 'course', 'quizzes');
const quiz = {};
for (const f of fs.readdirSync(QUIZ_DIR).filter(f => f.endsWith('.json')).sort()) {
  const j = JSON.parse(fs.readFileSync(path.join(QUIZ_DIR, f), 'utf8'));
  quiz[j.module] = { file: f.replace(/\.json$/, ''), questions: j.questions };
}
fs.writeFileSync(path.join(ROOT, 'generated', 'quiz-data.js'), '// Generated by tools/sync-course.js from the course quizzes. Do not edit.\nwindow.SAND_QUIZ = ' + JSON.stringify(quiz) + ';\n');
console.log('quiz-data.js:', Object.keys(quiz).length, 'modules');

// 2. figures, scenes, glyphs
const renderer = require(path.join(COURSE, 'course', 'visuals', 'render.js'));
const scenes = require(path.join(COURSE, 'course', 'visuals', 'scenes.js'));
const LESSONS = path.join(COURSE, 'course', 'visuals', 'lessons');
const figs = {}; let count = 0;
for (const file of fs.readdirSync(LESSONS).filter(f => /^m\d\d\.json$/.test(f)).sort()) {
  const key = file.replace('.json', '');
  for (const f of JSON.parse(fs.readFileSync(path.join(LESSONS, file), 'utf8'))) {
    const entry = { module: Number(key.slice(1)), section: f.section, family: f.family, title: f.title, caption: f.caption, nodes: f.nodes.map(n => ({ label: n.label, detail: n.detail })), scene: f.scene || null, returnLabel: f.returnLabel || null };
    try { entry.html = renderer.render(f, 'game-' + key); } catch (e) { entry.html = ''; entry.error = e.message; }
    if (f.scene) { const marker = 'game-' + key + '-' + f.section + '-arrow'; try { const s = scenes.scene(f.scene, marker); Object.assign(entry, { art: s.art, height: s.height, key: s.key, marker }); } catch (e) { entry.error = e.message; } }
    figs[key + '/' + f.section] = entry; count++;
  }
}
const bare = {};
for (const name of scenes.names) { try { const s = scenes.scene(name, 'bare-' + name + '-arrow'); bare[name] = { art: s.art, height: s.height, key: s.key, marker: 'bare-' + name + '-arrow' }; } catch (e) {} }
const GLYPHS = ['wafer', 'crystal', 'furnace', 'gas', 'mask', 'light', 'film', 'etch', 'transistor', 'wires', 'memory', 'package', 'test', 'rack', 'chip', 'clean', 'design', 'queue', 'heat', 'material'];
const glyphs = {};
try {
  const html = renderer.render({ section: 'glyphs', family: 'compare', title: 'g', caption: 'g', nodes: GLYPHS.map(g => ({ glyph: g, label: g, detail: g })) }, 'glyphs');
  const found = [...html.matchAll(/<svg viewBox="-54 -49 108 98"[^>]*>([\s\S]*?)<\/svg>/g)].map(m => m[1]);
  GLYPHS.forEach((g, i) => { if (found[i]) glyphs[g] = found[i]; });
} catch (e) { console.warn('glyph extraction failed', e.message); }
fs.writeFileSync(path.join(ROOT, 'generated', 'figures.js'), '// Generated by tools/sync-course.js from the course visuals. Do not edit.\nwindow.SG_FIGS = ' + JSON.stringify(figs) + ';\nwindow.SG_SCENES = ' + JSON.stringify(bare) + ';\nwindow.SG_GLYPHS = ' + JSON.stringify(glyphs) + ';\n');
console.log('figures.js:', count, 'figures,', Object.keys(bare).length, 'scenes,', Object.keys(glyphs).length, 'glyphs');

// 3. vendored widgets and stylesheets
const SITE = path.join(COURSE, 'site');
let n = 0;
for (const f of fs.readdirSync(path.join(SITE, 'widgets')).filter(f => f.endsWith('.js'))) { fs.copyFileSync(path.join(SITE, 'widgets', f), path.join(ROOT, 'course', 'widgets', f)); n++; }
for (const f of ['styles.css', 'widget-layout.js', 'section-figures.css']) fs.copyFileSync(path.join(SITE, f), path.join(ROOT, 'course', f));
console.log('vendored', n, 'widgets and 3 support files from', COURSE);
